### ISSUE TITLE
[Insight] Text files should end with a newline character - in app/config/config.yml, line 90

### ISSUE THREAD

**Issue by DRAKUN** [DRAKUN/Ecomm#4]
**[in app/config/config.yml, line 90](https://github.com/DRAKUN/Ecomm/blob/d7a2987cc83be316a25d4bb057447a7fea8f115b/app/config/config.yml#L90)**

> This file ends with no newline character. It won't render properly on a terminal, and it's considered a bad practice. Add a simple line feed as the last character to fix it.

```
######################

fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: Drak\UtilisateursBundle\Entity\Utilisateurs
```

---

_Posted from [SensioLabsInsight](https://insight.sensiolabs.com/projects/9e50c2e6-2146-4900-be9b-c74322edcb6b/analyses/1)_
